<a href="https://colab.research.google.com/github/VitorFRodrigues/tecprog1_Vitor_Rodrigues/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [1]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [2]:
arr = np.random.randint(1,101,100)
arr_max = arr.max()
arr_min = arr.min()
print(f'Array: {arr}\nValor máximo: {arr_max}\nValor minimo: {arr_min}')

Array: [ 76  24   6  46  16   7  59   8  88  83  16  81  35  14  73  85  81  94
  68  80  59   1  50   2  77   4  20  49  99  85  26  77  26  89  56  40
 100  90  88  71  43  92  87  45  57  52  37  16  14  57  82  94  84  83
  12  82  97  87  76  39  99  83  28  16  27  91  23  45  72  97  90  80
  53  88  53  54  20  15  97  36  20  99  11  17  78  32  79  62  53  97
   2  92  54  95  10  57  30  13  57  52]
Valor máximo: 100
Valor minimo: 1


In [3]:
# np.random.rand() dará valores aleatórios entre 0 e 1. Para modificar o intervalo deve ser feito:
# Intervalo [Inicio,Fim]
# arr = np.random.rand(100)*(Fim-Inicio) + Inicio

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [4]:
def modulo_vetor(arr):
  mod = np.sqrt((arr**2).sum())
  return mod

In [5]:
vetor = np.array([3, 4])
modulo = modulo_vetor(vetor)
print(f'Vetor: {vetor}\nModulo: {modulo}')

Vetor: [3 4]
Modulo: 5.0


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [7]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

In [6]:
# Solução
def calculate_eqm(y_pred, y_i):
  dif_quad = (y_pred - y_i)**2
  EQM = dif_quad.sum()/y_pred.size
  return EQM

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [8]:
def matriz_bordada(line, column):
  dim = (line, column)
  m_bord = np.zeros(dim)
  m_bord[:, 0] = 1
  m_bord[0, :] = 1
  m_bord[-1, :] = 1
  m_bord[:, -1] = 1
  return m_bord

In [9]:
matriz_bordada(5,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [10]:
def zero_borda(data):
  # Armazenando qtde de linhas e colunas em variável
  lin = data.shape[0]
  col = data.shape[1]
  # Executando matriz linhas e colunas com zeros
  m_lin = np.zeros((1,col))
  m_col = np.zeros((lin+2,1))
  # Concatenando as matrizes zero na matriz recebida
  zero_borda = np.concatenate((data, m_lin), axis=0)
  zero_borda = np.concatenate((m_lin, zero_borda), axis=0)
  zero_borda = np.concatenate((m_col, zero_borda), axis=1)
  zero_borda = np.concatenate((zero_borda, m_col), axis=1)
  return zero_borda

In [11]:
a = np.array([[1,2],[5,3],[4,6]])
zero_borda(a)

array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 5., 3., 0.],
       [0., 4., 6., 0.],
       [0., 0., 0., 0.]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [14]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [15]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

Media: 0.0074066829534309864


(64, 512)

In [16]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-242.70218701802614

In [17]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[ 0.59902781,  0.1484676 ,  1.75180008, ...,  0.21638197,
         0.00774071, -0.09293061],
       [-0.22863584, -0.52471579, -1.25647739, ...,  1.06137533,
        -0.00636608, -0.53243449],
       [ 0.39345576, -2.98635232,  1.85521472, ...,  0.53883779,
        -0.03903432,  1.69824897],
       ...,
       [ 0.69275264,  1.26740061, -0.54422276, ...,  0.04243515,
        -1.24335328,  1.00566562],
       [ 0.53789079, -0.62257919, -0.32719915, ...,  1.2518571 ,
        -1.0533378 , -0.43130688],
       [-0.70855669,  1.7022612 ,  0.61379738, ..., -1.63171413,
        -0.65806365, -0.50954891]])

In [18]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[ 5.91621123e-01,  1.41060913e-01,  1.74439340e+00, ...,
         2.08975290e-01,  3.34023872e-04, -1.00337293e-01],
       [-2.36042524e-01, -5.32122473e-01, -1.26388408e+00, ...,
         1.05396865e+00, -1.37727580e-02, -5.39841172e-01],
       [ 3.86049075e-01, -2.99375900e+00,  1.84780803e+00, ...,
         5.31431110e-01, -4.64410011e-02,  1.69084229e+00],
       ...,
       [ 6.85345960e-01,  1.25999393e+00, -5.51629440e-01, ...,
         3.50284663e-02, -1.25075997e+00,  9.98258937e-01],
       [ 5.30484104e-01, -6.29985871e-01, -3.34605833e-01, ...,
         1.24445042e+00, -1.06074448e+00, -4.38713560e-01],
       [-7.15963370e-01,  1.69485452e+00,  6.06390699e-01, ...,
        -1.63912081e+00, -6.65470335e-01, -5.16955592e-01]])

In [13]:
# Solução
def process_EEG_signal(X):
  media = X.sum()/X.size
  print(f'Media: {media}')
  X_process = X - media
  return X_process

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [20]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[-0.78583776,  0.17800818,  0.48485605, ..., -1.1813277 ,
        -0.48528758, -0.10836213],
       [ 0.10223314, -1.36120755, -0.05642711, ...,  0.48813133,
         0.49393159, -0.78526894],
       [-0.20449161, -0.42343826,  0.81833813, ..., -0.24057684,
        -0.93269023, -0.22255495],
       ...,
       [ 0.09465284, -0.00337108, -0.59412884, ..., -0.28804317,
        -0.619623  , -0.07222715],
       [ 1.39721335, -0.72030368,  0.30118502, ...,  0.55107773,
         0.31064211,  1.86034137],
       [-0.18439953, -0.42133861, -0.57967809, ...,  0.37680213,
         0.38363906,  1.83917673]])

In [21]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

Primeiro quartil (25%): -0.6836839575039974
Terceiro quartil (75%): 0.6663847838425603


In [22]:
is_outlier

array([[False,  True,  True, ..., False,  True,  True],
       [ True, False,  True, ...,  True,  True, False],
       [ True,  True, False, ...,  True, False,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [False, False,  True, ...,  True,  True, False],
       [ True,  True,  True, ...,  True,  True, False]])

In [23]:
outliers_count

2250

In [24]:
outliers

array([ 0.17800818,  0.48485605, -0.34853209, ..., -0.21474433,
        0.37680213,  0.38363906])

In [25]:
# Solução
def locate_outliers(X):
  quartil_25 = np.quantile(X, 0.25)
  print(f'Primeiro quartil (25%): {quartil_25}')
  quartil_75 = np.quantile(X, 0.75)
  print(f'Terceiro quartil (75%): {quartil_75}')
  is_outlier = np.where(((X > quartil_25) & (X < quartil_75)), True, False)
  outliers_count = np.count_nonzero(X*is_outlier)
  outliers = X[((X > quartil_25) & (X < quartil_75))]
  return is_outlier, outliers_count, outliers

Execução de exemplo prático para checar se a função *locate_outliers* está funcionando corretamente:

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
is_outlier, outliers_count, outliers = locate_outliers(a)

[[1 2 3]
 [4 5 6]]
Primeiro quartil (25%): 2.25
Terceiro quartil (75%): 4.75


In [27]:
is_outlier

array([[False, False,  True],
       [ True, False, False]])

In [28]:
outliers_count

2

In [29]:
outliers

array([3, 4])

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [30]:
np.arange(1, 21+1, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Questão 9

Crie um array de 10 com valores aleatórios

In [31]:
np.random.rand(10)

array([0.90930952, 0.58754597, 0.66795604, 0.63460499, 0.52071605,
       0.9290639 , 0.01585812, 0.62834944, 0.85569396, 0.05858562])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [32]:
def normalizacao(X):
  media = X.mean()
  desv_p = X.std()
  norm = (X - media)/desv_p
  return norm

In [33]:
Inicio = 54
Fim = 15
arr = np.random.rand(100)*(Fim-Inicio) + Inicio
norma = normalizacao(arr)
norma

array([ 1.50240004,  1.1324273 ,  1.43360765,  1.41126907,  1.04146717,
       -0.75395214, -0.84770162,  0.20025984, -1.53498299,  1.11597146,
        0.70781914,  0.07906098, -0.00247433,  0.72026381,  0.70180233,
       -0.75172371, -1.04213997,  1.00759795, -0.88420201, -1.10503342,
        0.07527121,  1.30353793, -1.24744231,  1.26344215,  1.17963642,
       -0.37730654, -1.65245653, -0.54171455,  0.81378454, -1.10597145,
       -0.91675027,  1.50295941, -0.14819699, -0.42214817,  0.95502932,
        1.49601516, -0.43288887, -1.09452603,  0.18059567, -0.78323089,
       -1.20039506,  0.50236164, -0.58236929, -1.71480326, -0.88660395,
       -0.42089682,  0.28551154, -0.73298952, -0.90165074, -1.33511236,
       -0.85550593, -0.04294193, -1.87250986,  1.47101217, -1.49416676,
       -0.48781078, -1.32513687,  1.40677658,  1.18262661, -0.35407011,
       -0.11263915, -0.05877161, -0.61894277,  0.79757299,  0.04978556,
       -0.11915276, -0.8599354 , -1.51683783,  1.51672016,  0.72

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [34]:
def analise_notas(notas, nota_corte=5):
  media = notas.mean()
  desv_p = notas.std()
  maior_7 = notas[(notas>7)].size
  reprovacoes = notas[(notas<nota_corte)].size
  menor_nota = notas.min()
  maior_nota = notas.max()

  analise = np.array([media, desv_p, maior_7, reprovacoes, menor_nota, maior_nota])
  return analise

In [35]:
notas = np.round(np.random.rand(100)*10, 2)

analise = analise_notas(notas)

print(f'Notas: {notas}\nAnálise: {analise}')

Notas: [6.49 1.65 5.26 0.27 7.33 1.68 9.54 1.54 2.   8.94 2.45 0.3  2.12 0.29
 9.81 7.81 8.34 8.95 9.79 9.81 3.86 0.27 1.4  9.93 3.66 3.73 7.33 2.93
 0.92 0.94 0.04 7.09 0.01 3.97 3.79 4.36 8.9  0.75 8.62 7.26 6.22 9.3
 0.39 1.96 7.64 9.44 4.72 4.37 4.38 6.39 6.94 8.25 1.99 7.9  2.34 9.52
 0.95 5.19 0.37 1.53 1.68 4.13 5.46 8.08 9.58 9.85 2.62 2.13 3.2  3.95
 0.05 4.28 5.94 7.24 5.64 1.64 6.89 6.34 9.04 1.51 3.44 2.93 8.9  5.7
 6.11 6.91 5.76 7.54 0.48 0.01 9.46 0.05 5.98 8.52 4.   1.86 1.12 6.06
 2.14 8.99]
Análise: [4.79130000e+00 3.19675262e+00 3.10000000e+01 5.20000000e+01
 1.00000000e-02 9.93000000e+00]
