<a href="https://colab.research.google.com/github/VitorFRodrigues/tecprog1_Vitor_Rodrigues/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [1]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [153]:
arr = np.random.randint(1,101,100)
arr_max = arr.max()
arr_min = arr.min()
print(f'Array: {arr}\nValor máximo: {arr_max}\nValor minimo: {arr_min}')

Array: [40 67 82 13 87 70 80  7 49 65 59 18 43 56 22 34 45  9 42 86 92 92 27 57
 51 14 18 84 69 18 54 72 16 10  7 24 10 76  4 65 35 47 10 47 39 57 92 67
  1 27 41 36 37 96 90 47  1 26 20  7 86 12 25 56 87 63 52 30 67  4 79 25
 20 96 71 92 64 46 97 32 62 56 25 72 81 44 51 18 43 28 61 85 32 55  1 45
 74 96 86 42]
Valor máximo: 97
Valor minimo: 1


In [4]:
# np.random.rand() dará valores aleatórios entre 0 e 1. Para modificar o intervalo deve ser feito:
# Intervalo [Inicio,Fim]
# arr = np.random.rand(100)*(Fim-Inicio) + Inicio

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [15]:
def modulo_vetor(arr):
  mod = np.sqrt((arr**2).sum())
  return mod

In [16]:
vetor = np.array([3, 4])
modulo = modulo_vetor(vetor)
print(f'Vetor: {vetor}\nModulo: {modulo}')

Vetor: [3 4]
Modulo: 5.0


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [22]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

In [21]:
# Solução
def calculate_eqm(y_pred, y_i):
  dif_quad = (y_pred - y_i)**2
  EQM = dif_quad.sum()/y_pred.size
  return EQM

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [45]:
def matriz_bordada(line, column):
  dim = (line, column)
  m_bord = np.zeros(dim)
  m_bord[:, 0] = 1
  m_bord[0, :] = 1
  m_bord[-1, :] = 1
  m_bord[:, -1] = 1
  return m_bord

In [49]:
matriz_bordada(5,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [86]:
def zero_borda(data):
  # Armazenando qtde de linhas e colunas em variável
  lin = data.shape[0]
  col = data.shape[1]
  # Executando matriz linhas e colunas com zeros
  m_lin = np.zeros((1,col))
  m_col = np.zeros((lin+2,1))
  # Concatenando as matrizes zero na matriz recebida
  zero_borda = np.concatenate((data, m_lin), axis=0)
  zero_borda = np.concatenate((m_lin, zero_borda), axis=0)
  zero_borda = np.concatenate((m_col, zero_borda), axis=1)
  zero_borda = np.concatenate((zero_borda, m_col), axis=1)
  return zero_borda

In [87]:
a = np.array([[1,2],[5,3],[4,6]])
zero_borda(a)

array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 5., 3., 0.],
       [0., 4., 6., 0.],
       [0., 0., 0., 0.]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [123]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [124]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

Media: 0.010328000243980133


(64, 512)

In [125]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-338.42791199474095

In [126]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[ 1.55229805, -0.20914547,  1.29241989, ...,  2.51643309,
         0.43219758, -0.53168319],
       [ 0.9265932 , -0.9413623 ,  1.14480129, ...,  0.05371631,
         1.44866726, -2.84700319],
       [ 1.64019262, -2.18057331, -0.99326766, ..., -1.1255483 ,
        -0.52567166,  0.11268322],
       ...,
       [ 0.86586549, -1.04561747, -0.76433181, ..., -0.54695337,
        -0.81462151, -1.62142071],
       [-0.53239293, -1.92194117,  0.00908536, ..., -0.04799896,
        -0.13644343, -1.04903051],
       [-1.33555215, -0.46437894, -0.47699952, ..., -0.55992617,
        -0.77881734,  1.45075166]])

In [127]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[ 1.54197005e+00, -2.19473470e-01,  1.28209189e+00, ...,
         2.50610509e+00,  4.21869581e-01, -5.42011193e-01],
       [ 9.16265199e-01, -9.51690304e-01,  1.13447329e+00, ...,
         4.33883092e-02,  1.43833926e+00, -2.85733119e+00],
       [ 1.62986462e+00, -2.19090131e+00, -1.00359566e+00, ...,
        -1.13587630e+00, -5.35999658e-01,  1.02355220e-01],
       ...,
       [ 8.55537493e-01, -1.05594547e+00, -7.74659809e-01, ...,
        -5.57281366e-01, -8.24949511e-01, -1.63174871e+00],
       [-5.42720929e-01, -1.93226917e+00, -1.24263933e-03, ...,
        -5.83269629e-02, -1.46771426e-01, -1.05935851e+00],
       [-1.34588015e+00, -4.74706940e-01, -4.87327520e-01, ...,
        -5.70254174e-01, -7.89145339e-01,  1.44042366e+00]])

In [109]:
# Solução
def process_EEG_signal(X):
  media = X.sum()/X.size
  print(f'Media: {media}')
  X_process = X - media
  return X_process

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [135]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[ 1.75280457, -0.76915889,  0.02775456, ...,  1.24942712,
        -1.81345118,  0.30889802],
       [-1.00775209, -0.57943692, -0.70117234, ..., -1.22876208,
         1.86483978, -0.42869096],
       [-1.62612183, -1.30702813, -0.44021219, ...,  0.03750182,
         0.21173823, -0.6938142 ],
       ...,
       [-2.32848689, -0.9236214 ,  0.06562631, ...,  0.22653145,
         0.90832422,  0.5073267 ],
       [-0.61366541, -0.65657644, -1.04171294, ..., -1.00039246,
         2.09251238, -1.01924256],
       [ 1.82200999,  0.48973575, -1.04609226, ..., -0.71496225,
         0.61904661, -1.55652154]])

In [136]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

Primeiro quartil (25%): 2.25
Terceiro quartil (75%): 4.75


In [137]:
is_outlier

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [138]:
outliers_count

49

In [139]:
outliers

array([2.33044605, 2.89164093, 2.3326025 , 2.47585057, 2.28515353,
       2.79819119, 2.8783963 , 2.67676836, 2.33134342, 2.7763863 ,
       2.78479516, 2.95603781, 2.69518302, 2.7605073 , 2.31898767,
       2.72351053, 2.70116987, 2.41470103, 2.2695089 , 2.75300125,
       2.47983864, 2.55275325, 2.76569082, 2.29088323, 2.26880609,
       2.4337773 , 2.34600214, 3.20191361, 3.38390409, 2.59010986,
       2.7429809 , 2.92241131, 2.56746704, 2.25036133, 2.4580696 ,
       2.7600742 , 3.42393503, 2.30441822, 2.58969399, 2.46861378,
       4.51805094, 2.47220195, 2.34941079, 2.53035304, 2.85610642,
       2.55758726, 2.49565174, 2.78330133, 3.32986808])

In [130]:
# Solução
def locate_outliers(X):
  quartil_25 = np.quantile(a, 0.25)
  print(f'Primeiro quartil (25%): {quartil_25}')
  quartil_75 = np.quantile(a, 0.75)
  print(f'Terceiro quartil (75%): {quartil_75}')
  is_outlier = np.where(((X > quartil_25) & (X < quartil_75)), True, False)
  outliers_count = np.count_nonzero(X*is_outlier)
  outliers = X[((X > quartil_25) & (X < quartil_75))]
  return is_outlier, outliers_count, outliers

Execução de exemplo prático para checar se a função *locate_outliers* está funcionando corretamente:

In [131]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
is_outlier, outliers_count, outliers = locate_outliers(a)

[[1 2 3]
 [4 5 6]]
Primeiro quartil (25%): 2.25
Terceiro quartil (75%): 4.75


In [132]:
is_outlier

array([[False, False,  True],
       [ True, False, False]])

In [133]:
outliers_count

2

In [134]:
outliers

array([3, 4])

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [141]:
np.arange(1, 21+1, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

## Questão 9

Crie um array de 10 com valores aleatórios

In [142]:
np.random.rand(10)

array([0.69204091, 0.24816785, 0.88264425, 0.38035782, 0.02138146,
       0.28955957, 0.51514411, 0.60320248, 0.22596557, 0.02639367])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [148]:
def normalizacao(X):
  media = X.mean()
  desv_p = X.std()
  norm = (X - media)/desv_p
  return norm

In [150]:
Inicio = 54
Fim = 15
arr = np.random.rand(100)*(Fim-Inicio) + Inicio
norma = normalizacao(arr)
norma

array([ 1.42940656,  0.3071065 ,  1.583358  , -1.41541803, -0.7356548 ,
       -1.71833245,  0.69448281, -0.78948243,  1.09927004,  0.06844974,
        0.51853653,  0.55681846, -1.49987585, -0.35449218,  0.92846319,
        0.31854293,  0.10202338,  0.2130155 ,  1.23806558, -0.49999526,
       -0.57731486, -1.52434251,  1.31289656, -0.15453184, -0.84918953,
       -0.24103677,  1.41820818,  1.31641453,  0.61940831, -0.20503766,
       -1.57079161, -0.35734793, -0.9513553 ,  0.10609361, -1.3050128 ,
       -1.17158788, -0.08536229, -1.33729861, -0.34245303,  1.43475385,
       -1.656593  ,  0.53764818,  0.77186919, -0.67564847, -0.640471  ,
        0.44825901, -1.09287037, -1.32709978, -1.57658416,  1.5254424 ,
       -0.77933305,  1.51430412,  0.56053615, -0.01648852,  0.07740736,
       -1.77643247,  1.35391731, -0.65798212, -1.5015108 ,  1.43268731,
       -0.76883956, -0.78647954, -0.22079474,  1.49307391,  0.32661529,
        1.20210659,  0.86501443, -1.49762185, -0.6771195 , -1.42

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [169]:
def analise_notas(notas, nota_corte=5):
  media = notas.mean()
  desv_p = notas.std()
  maior_7 = notas[(notas>7)].size
  reprovacoes = notas[(notas<nota_corte)].size
  menor_nota = notas.min()
  maior_nota = notas.max()

  analise = np.array([media, desv_p, maior_7, reprovacoes, menor_nota, maior_nota])
  return analise

In [172]:
notas = np.round(np.random.rand(100)*10, 2)

analise = analise_notas(notas)

print(f'Notas: {notas}\nAnálise: {analise}')

Notas: [ 0.55  4.65  6.33  9.77  3.44  6.53  6.41  2.83  3.07  9.81  2.57  3.93
  2.31  9.99  1.9   2.64  2.97  2.25  7.71  6.41  0.55  9.4   9.73  1.52
  8.14  7.36  7.55  7.2   3.17  8.96  8.68  0.85  7.17  2.78  7.6  10.
  1.31  2.94  2.6   3.78  1.17  6.74  4.94  8.56  4.09  7.7   2.16  4.27
  9.5   7.25  7.32  2.73  1.95  6.73  7.14  0.44  2.37  2.54  8.71  0.75
  0.12  8.4   1.8   2.21  7.88  6.96  2.6   4.14  7.12  4.39  9.2   5.12
  0.86  3.98  5.61  7.38  0.11  0.09  7.15  8.68  9.58  1.64  2.42  7.78
  6.61  9.31  4.66  7.11  4.64  9.05  0.8   8.71  7.53  0.83  8.74  7.77
  1.79  8.45  3.13  9.36]
Análise: [ 5.1813      3.05358237 40.         50.          0.09       10.        ]
