<a href="https://colab.research.google.com/github/VitorFRodrigues/tecprog1_Vitor_Rodrigues/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [3]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [4]:
arr = np.random.randint(1,101,100)
arr_max = arr.max()
arr_min = arr.min()
print(f'Array: {arr}\nValor máximo: {arr_max}\nValor minimo: {arr_min}')

Array: [100  88  81  77  87  36  97  67  14  31  83   6  18  26  15  99  32  52
  52  62  61  97  34  84  11  28  84  40  27  73  24  48   8  77  79  88
  36  67  11  77  93   8  46  63  53  20  24  88  71  86  42  74   2  87
  13  78  18  95  90  64   9  40  87  32  41  45  81  52  30  35  58  17
  45  68  36  79   5  85  83  64  29  13  52  99  19  56   4  32  61  88
  33  75  38  21  74  79  72  68  49  76]
Valor máximo: 100
Valor minimo: 2


In [5]:
# np.random.rand() dará valores aleatórios entre 0 e 1. Para modificar o intervalo deve ser feito:
# Intervalo [Inicio,Fim]
# arr = np.random.rand(100)*(Fim-Inicio) + Inicio

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [6]:
def modulo_vetor(arr):
  mod = np.sqrt((arr**2).sum())
  return mod

In [7]:
vetor = np.array([3, 4])
modulo = modulo_vetor(vetor)
print(f'Vetor: {vetor}\nModulo: {modulo}')

Vetor: [3 4]
Modulo: 5.0


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [10]:
# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666667

In [9]:
# Solução
def calculate_eqm(y_pred, y_i):
  dif_quad = (y_pred - y_i)**2
  EQM = dif_quad.sum()/y_pred.size
  return EQM

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [11]:
def matriz_bordada(line, column):
  dim = (line, column)
  m_bord = np.zeros(dim)
  m_bord[:, 0] = 1
  m_bord[0, :] = 1
  m_bord[-1, :] = 1
  m_bord[:, -1] = 1
  return m_bord

In [12]:
matriz_bordada(5,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [13]:
def zero_borda(data):
  # Armazenando qtde de linhas e colunas em variável
  lin = data.shape[0]
  col = data.shape[1]
  # Executando matriz linhas e colunas com zeros
  m_lin = np.zeros((1,col))
  m_col = np.zeros((lin+2,1))
  # Concatenando as matrizes zero na matriz recebida
  zero_borda = np.concatenate((data, m_lin), axis=0)
  zero_borda = np.concatenate((m_lin, zero_borda), axis=0)
  zero_borda = np.concatenate((m_col, zero_borda), axis=1)
  zero_borda = np.concatenate((zero_borda, m_col), axis=1)
  return zero_borda

In [14]:
a = np.array([[1,2],[5,3],[4,6]])
zero_borda(a)

array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 5., 3., 0.],
       [0., 4., 6., 0.],
       [0., 0., 0., 0.]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [15]:
# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões

(64, 512)

In [18]:
# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape

Media: 0.0005060889970005542


(64, 512)

In [19]:
# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()

-16.58352425371413

In [20]:
# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X

array([[-1.16043808,  0.76037416,  1.13115328, ..., -0.39755045,
         0.40698928, -0.37120093],
       [ 0.12122592, -0.35729734,  0.32972325, ...,  1.2261046 ,
        -0.51990086,  1.08458838],
       [-0.26113601,  1.45477744, -0.14717855, ..., -0.58462057,
        -0.26005291,  0.25365762],
       ...,
       [-0.94204269, -0.06341648,  0.03349791, ..., -2.35585728,
        -0.07542788,  0.5805745 ],
       [-0.24343542, -0.02088467, -0.48057388, ...,  1.07488963,
         1.06501571, -0.28330664],
       [-0.10021738, -0.85566276, -0.19099336, ..., -0.18086057,
        -1.28565471,  0.2356705 ]])

In [21]:
# Matriz após o processamento descrito no enunciado
X_processado

array([[-1.16094417,  0.75986807,  1.13064719, ..., -0.39805654,
         0.40648319, -0.37170702],
       [ 0.12071983, -0.35780342,  0.32921716, ...,  1.22559851,
        -0.52040695,  1.08408229],
       [-0.2616421 ,  1.45427135, -0.14768464, ..., -0.58512666,
        -0.260559  ,  0.25315153],
       ...,
       [-0.94254878, -0.06392257,  0.03299182, ..., -2.35636337,
        -0.07593396,  0.58006841],
       [-0.24394151, -0.02139076, -0.48107997, ...,  1.07438354,
         1.06450962, -0.28381273],
       [-0.10072347, -0.85616885, -0.19149945, ..., -0.18136666,
        -1.2861608 ,  0.23516441]])

In [17]:
# Solução
def process_EEG_signal(X):
  media = X.sum()/X.size
  print(f'Media: {media}')
  X_process = X - media
  return X_process

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [23]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[ 1.60314202, -1.00912457, -0.92163928, ...,  0.73167717,
         0.7998945 ,  0.38699034],
       [ 0.66660851, -1.22105126, -0.34671847, ...,  0.21156339,
         1.42788463, -1.28309068],
       [-1.04559338,  1.04190753,  0.26495025, ..., -0.56336535,
        -1.04702104,  0.61414901],
       ...,
       [-0.78941302,  0.45583694,  0.66474851, ...,  0.07835782,
        -0.75768462,  0.95677454],
       [ 0.22373212,  0.65794883,  0.42011096, ...,  1.08649351,
        -0.13027335, -1.37283291],
       [-0.82043725, -1.39241041, -1.02206278, ..., -0.6459253 ,
         0.29861233, -0.0555574 ]])

In [24]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

Primeiro quartil (25%): -0.6387547400828347
Terceiro quartil (75%): 0.6842192500069757


In [25]:
is_outlier

array([[False, False, False, ..., False, False,  True],
       [ True, False,  True, ...,  True, False, False],
       [False, False,  True, ...,  True, False,  True],
       ...,
       [False,  True,  True, ...,  True, False, False],
       [ True,  True,  True, ..., False,  True, False],
       [False, False, False, ..., False,  True,  True]])

In [26]:
outliers_count

2250

In [27]:
outliers

array([ 0.37088797, -0.29988984, -0.11546375, ..., -0.32029597,
        0.29861233, -0.0555574 ])

In [22]:
# Solução
def locate_outliers(X):
  quartil_25 = np.quantile(X, 0.25)
  print(f'Primeiro quartil (25%): {quartil_25}')
  quartil_75 = np.quantile(X, 0.75)
  print(f'Terceiro quartil (75%): {quartil_75}')
  is_outlier = np.where(((X > quartil_25) & (X < quartil_75)), True, False)
  outliers_count = np.count_nonzero(X*is_outlier)
  outliers = X[((X > quartil_25) & (X < quartil_75))]
  return is_outlier, outliers_count, outliers

Execução de exemplo prático para checar se a função *locate_outliers* está funcionando corretamente:

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
is_outlier, outliers_count, outliers = locate_outliers(a)

In [ ]:
is_outlier

In [ ]:
outliers_count

In [ ]:
outliers

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [ ]:
np.arange(1, 21+1, 2)

## Questão 9

Crie um array de 10 com valores aleatórios

In [ ]:
np.random.rand(10)

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [ ]:
def normalizacao(X):
  media = X.mean()
  desv_p = X.std()
  norm = (X - media)/desv_p
  return norm

In [ ]:
Inicio = 54
Fim = 15
arr = np.random.rand(100)*(Fim-Inicio) + Inicio
norma = normalizacao(arr)
norma

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [ ]:
def analise_notas(notas, nota_corte=5):
  media = notas.mean()
  desv_p = notas.std()
  maior_7 = notas[(notas>7)].size
  reprovacoes = notas[(notas<nota_corte)].size
  menor_nota = notas.min()
  maior_nota = notas.max()

  analise = np.array([media, desv_p, maior_7, reprovacoes, menor_nota, maior_nota])
  return analise

In [ ]:
notas = np.round(np.random.rand(100)*10, 2)

analise = analise_notas(notas)

print(f'Notas: {notas}\nAnálise: {analise}')